### PR TITLE
Adding Multi-Line tasks. Fixes #2

### LINKED ISSUE #2: Multi-line tasks
I really don't like the idea that a single task must be on one line only. It makes it very inflexible which is in stark contrast to the _todo.txt is just a text file_ thing.

When a task gets longer it becomes unreadable, especially if you don't like using text wrapping in your editor.
Some examples:
```
(A) Figure out why this doesn't work: (code was just pasted in)
    for (let ... {
    }

(B) Fix this error message: (message was just pasted in)
    Assertion failed: 
    bla bla bla...

(C) This is a very simple bullet list consisting of things
    I don't want to be individual tasks:
    - asdf
    - asdf
    - asdf

(D) I think that word wrapping is a property of the text and not the
editor, so I want to add the word breaks in myself and not have
to rely on a editor/client to do it for me.

(E) 2000-01-01 2000-01-02 rec:12d-1m @asdf +qwerty
I can use the first line for the 'metadata' and keep the actual task
nice and clean.
```

There should be some way to add multi-line support in a simple, mostly backwards-compatible way. Off the top of my head:
```
(A) this is a single task
(B) this is another single task

---
(C) A task enclosed between lines only consisting of dashes
is treated as a
multi-line task.
---

---
(D) this is another
multi-line
task
---

(D) this is a single task
(D) this is a single task

---
(D) 2000-01-01 2001-01-01 rec:12d-1m +my_project

This is another long task I want to be split off into multiple
lines to make it readable. Maybe I might throw in some simple
bullet list:
  - asdf
  - asdf
  - asdf
---
```

### PR DESCRIPTION
**Pull request by dessalines**
Adding multi-line tasks.

### CODE REVIEW

**Comment by dessalines** [comment]
Any updates?

**Comment by dessalines** [comment]
This project is so dead.

**Comment by nelsonblaha** [comment]
"Feature Complete"

**Comment by dessalines** [comment]
@nelsonblaha should I start a fork? And I mean a new repo, not just a fork.

**Comment by nelsonblaha** [comment]
I'm not interested in multi-line tasks so I wouldn't be switching to it yet. But it sure wouldn't hurt anything to have more options out there!

**Comment by dessalines** [comment]
This project is dead, and I've written a converter to convert a todo.txt file to a tasks.org import file. That has multi-line notes / descriptions that can span multiple lines.

**Pull request closed without merging**
